baseURL = "https://msfjarvis.dev/"
title = "Harsh Shandilya"
theme = ["github.com/adityatelange/hugo-PaperMod"]

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
pygmentsUseClasses = true
pygmentsCodefences = true
noClasses = false

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 10

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 12

[[menu.main]]
name = "Now"
url = "/now"
weight = 13

[[menu.main]]
name = "Uses"
url = "/uses"
weight = 15

[minify]
disableXML = true

[mediaTypes."text/plain"]
suffixes = ["txt"]

[outputFormats.TXT]
name = "TXT"
mediaType = "text/plain"
isPlainText = true
notAlternative = false
rel = "alternate"

[outputs]
page = ["HTML", "TXT"]

[params]
env = "production"
defaultTheme = "auto"
description = "Recovering Android and Kotlin developer, amateur Rustacean"
images = ["android-chrome-512x512.webp"]
author = "Harsh Shandilya"

comments = true
utterancesRepo = "msfjarvis/msfjarvis.dev"

showShareButtons = true
shareButtons = ["linkedin", "reddit", "telegram"]
showReadingTime = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showRssButtonInSectionTermList = true
ShowFullTextinRSS = true
showToc = true
social = true

[params.editPost]
url = "https://github.com/msfjarvis/msfjarvis.dev/edit/main/content/"
text = "Suggest Changes"
appendFilePath = true

[params.assets]
disableHLJS = true
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.webp"
favicon32x32 = "favicon-32x32.webp"
apple_touch_icon = "apple-touch-icon.png"
safari_pinned_tab = "mask-icon.svg"

[params.homeInfoParams]
title = "Hi ðŸ‘‹, I am Harsh"
content = "Recovering Android and Kotlin developer, amateur Rustacean"

[[params.socialIcons]]
title = "GitHub"
name = "github"
url = "https://github.com/msfjarvis"

[[params.socialIcons]]
title = "Mastodon (Android)"
name = "mastodon"
url = "https://androiddev.social/@msfjarvis"

[[params.socialIcons]]
title = "Mastodon (Gaming)"
name = "mastodon"
url = "https://mstdn.games/@msfjarvis"

[[params.socialIcons]]
title = "Gitea"
name = "gitea"
url = "https://git.msfjarvis.dev/explore/repos"

[[params.socialIcons]]
title = "RSS"
name = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
tag = "tags"
category = "categories"
