baseurl = "https://msfjarvis.dev/"
languageCode = "en-us"
title = "Harsh Shandilya"
theme = ["github.com/msfjarvis/hugo-social-metadata", "ezhil"]
pygmentsstyle = "tango"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
author = "Harsh Shandilya"
ignoreErrors = ["error-remote-getjson"]

[module]
[[module.imports]]
  path = "github.com/msfjarvis/hugo-social-metadata"

[params]
  description = "Android developer, Kotlin fanatic and wannabe Rustacean"
  subtitle = "Android developer, Kotlin fanatic and wannabe Rustacean"
  keywords = "homepage, blog, android, kotlin, rust"
  twitterUsername = "@msfjarvis"
  socialImage = "android-chrome-512x512.webp"
  mainSections = ["posts"]
  mode = "light"
  utterancesRepo = "msfjarvis/msfjarvis.dev"
  utterancesTheme = "github-light"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/posts"

[[menu.main]]
  identifier = "uses"
  name = "uses"
  title = "Uses"
  url = "/uses"

[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "Projects"
  url = "/projects"

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/msfjarvis"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/msfjarvis"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

# Enable tags.
[taxonomies]
  tag = "tags"
  category = "categories"
